name: Release and Build Docker Image

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.semver.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tag
        id: semver
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create GitHub release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: ${{ env.NEW_VERSION }}
      #     release_name: Release ${{ env.NEW_VERSION }}
      #     body: |
      #       Changes in this release:
      #       ${{ github.event.pull_request.title }}
      #     draft: false
      #     prerelease: false

  build:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Use the new tag
        run: |
          echo "Tag from previous job: ${{ needs.release.outputs.tag }}"
          echo "NEW_VERSION=${{ needs.release.outputs.tag }}" >> $GITHUB_ENV

      # - name: Extract current tag
      #   id: extract_tag
      #   run: |
      #     # Extract the tag and remove the leading 'v' if it exists
      #     TAG=${GITHUB_REF#refs/tags/}
      #     CLEAN_TAG=${TAG#v}
      #     echo "TAG=$CLEAN_TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.NEW_VERSION }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}